import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useLocalStorage } from "usehooks-ts";
import { LoginPaper } from "../components/LoginPaper";
import { MenuUser } from "../components/MenuUser";
import { Footer } from "../components/Footer";

const Home: NextPage = () => {

  const [paperToken, setPaperToken] = useLocalStorage<string | boolean>(
    "paper-token",
    false
  );

  const [log, isLogged] = useState<Boolean | undefined>(undefined);

  useEffect(() => {
    if (!paperToken) {
      isLogged(false);
    } else {
      isLogged(true);
    }
  }, [paperToken]);

  return (
    <div className="flex flex-col min-h-screen font-medium" data-theme="corporate">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="grid grow place-items-center bg-sky-100">
        {log !== undefined &&
        <>
        {log && <MenuUser/>}
        {!log && (
          <>
          <div className="max-w-sm flex flex-col items-center">
            <div className="text-center">
              <div className="text-2xl">
                Hi, you are ready to claim you first certificate! 🥳
              </div>
              <div className="text-lg">
                 Please 🙏, click the bottom below and register a new account. Only your email is required 📧
              </div>
            </div>
            <div className="pt-4">
              <LoginPaper />
            </div>
          </div>
          </>
        )}</>}
      </main>
      {!log && <Footer/>}
    </div>
  );
};

export default Home;
